django_project/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

import os

admin_word = os.environ.get("ADMIN_WORD")

urlpatterns = [
    path("", views.home, name="home"),
    path("mmestore/", include("mmestore.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(f"{admin_word}/", admin.site.urls),
]

admin.site.site_header = "Mmes Creations LLC"
admin.site.site_title = "Mmes Store Inventory"
admin.site.index_title = "Mmes Store Inventory"

mmestore/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("categories", views.CategoriesListView.as_view(), name="categories"),
    path(f"category/<int:category_id>/", views.category, name="category"),
    path(
        f"category_add_craft_item/<int:category_id>/",
        views.category_add_craft_item,
        name="category_add_craft_item",
    ),
    path(f"craft_item/<item_number>/", views.craft_item, name="craft_item"),
    path(
        f"craft_item_ship/<item_number>/", views.craft_item_ship, name="craft_item_ship"
    ),
    path(f"item_lookup", views.item_lookup, name="item_lookup"),
    path(f"more_craft_fairs", views.more_craft_fairs, name="more_craft_fairs"),
    path(f"sold_at_fair/<fair_id>/", views.sold_at_fair, name="sold_at_fair"),
]

mmestore/models.py
from django.db import models
from datetime import datetime


class Category(models.Model):
    cat_name = models.CharField(unique=True, max_length=200)
    cat_code = models.CharField(max_length=1, null=True, blank=False)

    def __str__(self):
        return self.cat_name


class CraftFair(models.Model):
    fair_name = models.CharField(max_length=200)
    fair_url = models.URLField(default=None, blank=True, null=True, max_length=200)
    address = models.CharField(default=None, blank=True, null=True, max_length=200)
    city = models.CharField(default=None, blank=True, null=True, max_length=200)
    state = models.CharField(default="IN", blank=True, null=True, max_length=200)
    zip = models.CharField(default=None, blank=True, null=True, max_length=20)
    first_start_time = models.DateTimeField(default=datetime.now)
    first_end_time = models.DateTimeField(default=datetime.now)
    second_start_time = models.DateTimeField(default=None, blank=True, null=True)
    second_end_time = models.DateTimeField(default=None, blank=True, null=True)
    third_start_time = models.DateTimeField(default=None, blank=True, null=True)
    third_end_time = models.DateTimeField(default=None, blank=True, null=True)
    photo_fair = models.URLField(
        default="https://live.staticflickr.com/7893/31652682857_186874f73f_w.jpg",
        blank=True,
        null=True,
        max_length=200,
    )
    photo_fair_width = models.IntegerField(default=400, blank=True, null=True)
    photo_fair_height = models.IntegerField(default=300, blank=True, null=True)

    def __str__(self):
        return f"{self.fair_name} {self.first_start_time.year}"


class CraftItem(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    item_number = models.CharField(unique=True, max_length=16)
    description = models.CharField(default=None, blank=True, null=True, max_length=200)
    photo_front = models.URLField(default=None, blank=True, null=True, max_length=200)
    photo_front_width = models.IntegerField(default=None, blank=True, null=True)
    photo_front_height = models.IntegerField(default=None, blank=True, null=True)
    photo_back = models.URLField(default=None, blank=True, null=True, max_length=200)
    photo_back_width = models.IntegerField(default=None, blank=True, null=True)
    photo_back_height = models.IntegerField(default=None, blank=True, null=True)
    price = models.FloatField(default=None, blank=True, null=True)
    shipping = models.FloatField(default=None, blank=True, null=True)
    has_it_been_sold = models.BooleanField(default=False)
    craft_fair = models.ForeignKey(
        CraftFair, blank=True, null=True, on_delete=models.CASCADE
    )
    width = models.FloatField(default=None, blank=True, null=True)
    height = models.FloatField(default=None, blank=True, null=True)
    depth = models.FloatField(default=None, blank=True, null=True)
    dress_size = models.FloatField(default=None, blank=True, null=True)
    pay_code = models.CharField(default=None, blank=True, null=True, max_length=10000)

    def __str__(self):
        return self.description

mmestore/forms.py
from django import forms
from django.core.exceptions import ValidationError

import re


class ItemNumberForm(forms.Form):
    item_num = forms.CharField(label="Item Number", max_length=6)


class CategoryAddCraftItemForm(forms.Form):
    item_number = forms.CharField(label="Item Number", max_length=4)
    description = forms.CharField(label="Description", max_length=200)
    price = forms.FloatField(label="Price")
    shipping = forms.FloatField(label="Shipping Charge")
    width = forms.FloatField(label="Width", required=False)
    height = forms.FloatField(label="Height", required=False)
    depth = forms.FloatField(label="Depth", required=False)
    dress_size = forms.FloatField(label="Dress Size", required=False)

    def clean_item_number(self):
        data = self.cleaned_data["item_number"]
        p = re.compile(f"[A-Z0-9][0-9][0-9][0-9]$")
        if not p.match(data):
            raise ValidationError(
                ("Item number is not formatted correctly." "Please use default value."),
                code="invalid",
            )
        return data

django_project/views.py
from django.shortcuts import redirect
import os


def home(request):
    return redirect("/mmestore", request)

mmestore/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.decorators import login_required

from .models import Category, CraftItem, CraftFair
from .forms import ItemNumberForm, CategoryAddCraftItemForm
from .viewlogic.fair_info import get_fair_details, sort_fairs
from .viewlogic.next_craft_item_number import get_next_craft_item_default


def index(request):
    return redirect("item_lookup")


class CategoriesListView(ListView):
    model = Category
    template_name = "mmestore/categories.html"
    ordering = "cat_name"


def category(request, category_id):
    category_item = get_object_or_404(Category, pk=category_id)
    craft_items = CraftItem.objects.filter(
        category=category_id, has_it_been_sold=False
    ).order_by("-item_number")
    context = {
        "category_name": category_item.cat_name,
        "category_id": category_id,
        "items": craft_items,
    }
    return render(request, "mmestore/category.html", context)


def craft_item(request, item_number):
    item = get_object_or_404(CraftItem, item_number=item_number)
    item_category = item.category.cat_name
    context = {
        "item": item,
        "category_name": item_category,
    }

    if item.has_it_been_sold:
        return render(request, "mmestore/craft_item_sold.html", context)

    return render(request, "mmestore/craft_item.html", context)


def craft_item_ship(request, item_number):
    item = get_object_or_404(CraftItem, item_number=item_number)
    if item.shipping:
        ship_price = item.price + item.shipping
    else:
        ship_price = item.price
    item_category = item.category.cat_name
    context = {
        "item": item,
        "category_name": item_category,
        "ship_price": ship_price,
    }
    return render(request, "mmestore/craft_item_ship.html", context)


def item_lookup(request):

    if request.method == "POST":
        form = ItemNumberForm(request.POST)
        if form.is_valid():
            item_num = form.cleaned_data["item_num"]
            return redirect("craft_item_ship", item_number=item_num)

    else:
        fair, fair_info = get_fair_details()
        form = ItemNumberForm()
        context = {
            "fair": fair,
            "form": form,
            "fair_info": fair_info,
        }
        return render(request, "mmestore/item_lookup.html", context)


def more_craft_fairs(request):
    fairs_future, fairs_past, fair_in_progress = sort_fairs()
    context = {
        "fairs_future": fairs_future,
        "fairs_past": fairs_past,
        "fair_in_progress": fair_in_progress,
        "last_fair": fairs_past[0],
    }
    return render(request, "mmestore/more_craft_fairs.html", context)


def sold_at_fair(request, fair_id):
    fair = get_object_or_404(CraftFair, pk=fair_id)
    craft_items = CraftItem.objects.filter(
        craft_fair_id=fair_id, has_it_been_sold=True
    ).order_by("-item_number")
    context = {
        "fair": fair.__str__,
        "items": craft_items,
    }
    return render(request, "mmestore/sold_at_fair.html", context)

@login_required
def category_add_craft_item(request, category_id):
    category = Category.objects.get(pk=category_id)
    if request.method == "POST":
        form = CategoryAddCraftItemForm(request.POST)
        if form.is_valid():
            add_item = CraftItem(
                category=category,
                item_number=form.cleaned_data["item_number"],
                description=form.cleaned_data["description"],
                price=form.cleaned_data["price"],
                shipping=form.cleaned_data["shipping"],
                width=form.cleaned_data["width"],
                height=form.cleaned_data["height"],
                depth=form.cleaned_data["depth"],
                dress_size=form.cleaned_data["dress_size"],
            )
            add_item.save()
        return redirect("item_lookup")
    else:
        id_default = get_next_craft_item_default(category_id)
        form = CategoryAddCraftItemForm(initial={"item_number": id_default})
        context = {
            "form": form,
            "category": category.cat_name,
        }
        return render(request, "mmestore/category_add_craft_item.html", context)

django_project/templates/mmestore/categories.html
{% extends "base.html" %}

{% block title %}Mme's Creations Categories{%  endblock %}

{% block content %}
    <h1>View by Category:</h1>

    {% if category_list %}

        <ul>

        {% for category in category_list %}
            <li><h2><a href="{% url 'category' category.pk %}">
                {{ category.cat_name }}</a> 
                {% if user.is_authenticated %}
                <span class="add-item" ><a href="{% url 'category_add_craft_item' category.pk %}">+</a></span>
                {% endif %}
                </h2>                 
            </li>
        {% endfor %}

        </ul>
    {%  else %}
        <p>No categories are currently in the database.</p>

    {% endif %}



{% endblock %}

{% block side-content %}
    <img class="col6" src="https://live.staticflickr.com/65535/50580339178_0c7e180a51_w.jpg">
{% endblock %}

django_project/templates/mmestore/category.html
{% extends "base.html" %}

{% block title %}Mme's Creations: {{ category_name }} {%  endblock %}

{% block full-content %}
<h1>Category: {{ category_name }}</h1>

{% if user.is_authenticated %}
    <h2><a href="{% url 'category_add_craft_item' category_id %}">Add more {{ category_name }}</a></h2>
{% endif %}

    {% if items %}

        {% for item in items %}
            <div id="cat_break" class="column-12"></div>

                <div class="column-12" id="cat_item">
                    <div class="column-6">
                    <a href="{% url 'craft_item_ship'  item.item_number %}">
                    <img class="col6" src="{{ item.photo_front }}" alt="{{ item.description }}">
                    </a>
                    </div>

                    <div class="column-6">
                    <h4>{{ item.description }}</h4>
                    <h4>Price: ${{ item.price|floatformat:2 }}</h4>
                    <h4>Item Number: {{ item.item_number }}</h4>
                    </div>
                </div>
            <br clear="both">


        {% endfor %}

    {% if user.is_authenticated %}
        <h2><a href="{% url 'category_add_craft_item' category_id %}">Add more {{ category_name }}</a></h2>
    {% endif %}

    {%  else %}
        <h3>No {{ category_name.lower }} items are currently listed in the database.</h3>
    {% endif %}
{% endblock %}

django_project/templates/mmestore/category_add_craft_item.html
{% extends 'base.html' %}

{% block content %}

    <div id="content">

        <h2>Add {{ category }} item to database:</h2>
        
        <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
        </form>
    
    </div>

{% endblock %}

django_project/templates/mmestore/craft_item.html
{% extends "base.html" %}

{% block title %}Mme's Creations: {{ category_name }} - {{ item.description }} {%  endblock %}

{% block full-content %}
<h1>{{ category_name }}:</h1>
<h2> {{ item.item_number }} - {{ item.description }}</h2>
{% endblock %}

{% block content %}


    {% if item.photo_front %}
    <img src="{{ item.photo_front }}" width="{{ item.photo_front_width }}" height="{{ item.photo_front_height }}"
    alt="{{ item.description }}">
    {% endif %}
    <br>

    {% if item.photo_back %}
    <img src="{{ item.photo_back }}" width="{{ item.photo_back_width }}" height="{{ item.photo_back_height }}"
    alt="{{ item.description }}">
    {% endif %}

    <h3>Price: ${{ item.price|floatformat:2 }}</h3>

    <ul>
        {% if item.width %}
        <li><h4>Width: {{ item.width }}"</h4></li>
        {% endif %}

        {% if item.height %}
        <li><h4>Height: {{ item.height }}"</h4></li>
        {% endif %}

        {% if item.depth %}
        <li><h4>Depth: {{ item.depth }}"</h4></li>
        {% endif %}

        {% if item.dress_size %}
        <li><h4>Dress Size: {{ item.dress_size }}"</h4></li>
        {% endif %}
    </ul>



{% endblock %}

{% block side-content %}
    <h2>Purchase for In Person Events ONLY</h2>
    <table>
        <tr>
            <td>Price:</td>
            <td>${{ item.price|floatformat:2 }}</td>
        </tr>
        <tr>
            <td>***In person purchase ONLY***</td>
            <td>FREE</td>
        </tr>
        <tr>
            <td>Subtotal:</td>
            <td>${{ item.price|floatformat:2 }}</td>
        </tr>
    </table>
    <br>
    <h3>To have it shipped for ${{ item.shipping|floatformat:2 }} more to a US address: <a href="{% url 'craft_item_ship' item.item_number %}">CLICK HERE</a></h3>

    <script src="https://www.paypal.com/sdk/js?client-id=Aae9cvv-osUTNKCa2L5sH_redeLOqdct6RB9u7nYivp2-jkfNmdTCQJM-WYxXcN6iZbRHancN5gwVyPl"> // Replace YOUR_SB_CLIENT_ID with your sandbox client ID
    </script>

    <div id="paypal-button-container"></div>

    <!-- Add the checkout buttons, set up the order and approve the order -->
    <script>
      paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '{{ item.price|floatformat:2 }}'
              },
              description: '{{ category_name }} - {{ item.description }} - {{ item.item_number }} - ***In person purchase ONLY***'
            }]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            alert('Transaction completed by ' + details.payer.name.given_name);
          });
        }
      }).render('#paypal-button-container'); // Display payment options on your web page
    </script>
{% endblock %}

django_project/templates/mmestore/craft_item_ship.html
{% extends "base.html" %}

{% block title %}Mme's Creations: {{ category_name }} - {{ item.description }} {%  endblock %}

{% block full-content %}
<h1>{{ category_name }}:</h1>
<h2> {{ item.item_number }} - {{ item.description }}</h2>
{% endblock %}


{% block content %}
    {% if item.photo_front %}
    <img src="{{ item.photo_front }}" width="{{ item.photo_front_width }}" height="{{ item.photo_front_height }}"
    alt="{{ item.description }}">
    {% endif %}
    <br>

    {% if item.photo_back %}
    <img src="{{ item.photo_back }}" width="{{ item.photo_back_width }}" height="{{ item.photo_back_height }}"
    alt="{{ item.description }}">
    {% endif %}

    <h3>Price: ${{ item.price|floatformat:2 }}</h3>

    <ul>
        {% if item.width %}
        <li><h4>Width: {{ item.width }}"</h4></li>
        {% endif %}

        {% if item.height %}
        <li><h4>Height: {{ item.height }}"</h4></li>
        {% endif %}

        {% if item.depth %}
        <li><h4>Depth: {{ item.depth }}"</h4></li>
        {% endif %}

        {% if item.dress_size %}
        <li><h4>Dress Size: {{ item.dress_size }}"</h4></li>
        {% endif %}
    </ul>



{% endblock %}

{% block side-content %}
<h2>Purchase via PayPal below for shipping to a United States address</h2>
    <table>
        <tr>
            <td>Price:</td>
            <td>${{ item.price|floatformat:2 }}</td>
        </tr>
        <tr>
            <td>Shipping & Handling:</td>
            <td>${{ item.shipping|floatformat:2 }}</td>
        </tr>
        <tr>
            <td>Subtotal:</td>
            <td>${{ ship_price|floatformat:2 }}</td>
        </tr>
    </table>
    <br>

    <script src="https://www.paypal.com/sdk/js?client-id=AUmj7jR64NWeHuwoiF1CqTJ2pzQXRYTtLaaTaszvcCTuhsYZrrazqjKXHr_IP9l3tbvxHsdN7hd_uEr6"> // Replace YOUR_SB_CLIENT_ID with your sandbox client ID
    </script>

    <div id="paypal-button-container"></div>

    <!-- Add the checkout buttons, set up the order and approve the order -->
    <script>
      paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '{{ ship_price|floatformat:2 }}'
              },
              description: '{{ category_name }} - {{ item.description }} - {{ item.item_number }} - for shipping to U.S. address'
            }]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            alert('Transaction completed by ' + details.payer.name.given_name);
          });
        }
      }).render('#paypal-button-container'); // Display payment options on your web page
    </script>
{%  endblock %}

django_project/templates/mmestore/craft_item_sold.html
{% extends "base.html" %}

{% block moremeta %}
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Ensures optimal rendering on mobile devices. -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" /> <!-- Optimal Internet Explorer compatibility -->
{% endblock %}

{% block title %}Mme's Creations: {{ category_name }} - {{ item.description }} {%  endblock %}

{% block content %}

<h1>{{ category_name }}: {{ item.item_number }} - {{ item.description }}</h1>
    <h2 class="sold_out">*** This item has been sold out - Thank you for your interest ***</h2>

    {% if item.photo_front %}
    <img src="{{ item.photo_front }}" width="{{ item.photo_front_width }}" height="{{ item.photo_front_height }}"
    alt="{{ item.description }}">
    {% endif %}
    <br>

    {% if item.photo_back %}
    <img src="{{ item.photo_back }}" width="{{ item.photo_back_width }}" height="{{ item.photo_back_height }}"
    alt="{{ item.description }}">
    {% endif %}

    <h3>Price: ${{ item.price|floatformat:2 }}</h3>

    <ul>
        {% if item.width %}
        <li><h4>Width: {{ item.width }}"</h4></li>
        {% endif %}

        {% if item.height %}
        <li><h4>Height: {{ item.height }}"</h4></li>
        {% endif %}

        {% if item.depth %}
        <li><h4>Depth: {{ item.depth }}"</h4></li>
        {% endif %}

        {% if item.dress_size %}
        <li><h4>Dress Size: {{ item.dress_size }}"</h4></li>
        {% endif %}
    </ul>

{% endblock %}

django_project/templates/mmestore/index.html
{% extends "base.html" %}

{% block title %}Mme's Creations{%  endblock %}

{% block content %}

    <h1>Mme's Creations</h1>

    <h2>Shop by <a href="categories">Category</a> </h2>
{% endblock %}

django_project/templates/mmestore/item_lookup.html
{% extends "base.html" %}

{% block title %}Mme's Creations{% endblock %}

{% block full-content %}

    {% if not fair_info.future_none %}

        <div {% if fair_info.in_progress %}id="in-progress"{% endif %}>


            <img class="col6" id="fair_pic" src="{{ fair.photo_fair }}" width="{{ fair.photo_fair_width }}" height="{{ fair.photo_fair_height }}">

            <p>
            {% if fair_info.in_progress %} <b>We are at a Craft Fair Today - Come see us:</b> {% endif %}

            {% if not fair_info.in_progress %} <b>Come to our Next Craft Fair:</b> {% endif %}

                <a href="{{ fair.fair_url }}">{{ fair.fair_name }}</a></p>

            <ul>
            <li>{{ fair.first_start_time|date:"l"}}, {{ fair.first_start_time.date }}: {{ fair.first_start_time.time }} to {{ fair.first_end_time.time }} ET</li>

            {% if fair.second_start_time %}
                <li>{{ fair.second_start_time|date:"l"}}, {{ fair.second_start_time.date }}: {{ fair.second_start_time.time }} to {{ fair.second_end_time.time }} ET</li>
            {% endif %}

            {% if fair.third_start_time %}
                <li>{{ fair.third_start_time|date:"l"}}, {{ fair.third_start_time.date }}: {{ fair.third_start_time.time }} to {{ fair.third_end_time.time }} ET</li>
            {% endif %}
            </ul>

            <p><b>Location:</b> {{ fair.address }} {{ fair.city }}, {{ fair.state }}</p>

            <h3>See <a href="more_craft_fairs">More Craft Fairs</a></h3>


        </div>
        
    {% endif %}

{%  endblock %}

{% block content %}



    <div id="content">

    <h2>Shop by <a href="categories">Category</a> </h2>

    <h2>Shop by item number:</h2>

    <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
    </form>

    <h3>This site is only set for purchasing one item at a time.</h3>
    <p>If you are interesting in purchase more than one item,
        especially if you want items shipped together at a lower cost, please
        send a text message to 
        Marietta Harrold (765) 271-1083 for a quote on a bundle.</p>
    </div>

{% endblock %}

{% block side-content %}
    <img class="col6" src="https://live.staticflickr.com/65535/50580321443_d9edcc5200_w.jpg">
{% endblock %}

django_project/templates/mmestore/more_craft_fairs.html
{% extends "base.html" %}

{% block title %}Mme's Creations Craft Fairs{%  endblock %}

{% block full-content %}

    {% if fair_in_progress %}
        <div class="column-12" id="in-progress">
        <img class="col6" id="fair_pic" src="{{ last_fair.photo_fair }}" width="{{ last_fair.photo_fair_width }}" height="{{ last_fair.photo_fair_height }}">
        <h1>Come see us today at <a href="{{ last_fair.fair_url }}">{{ last_fair.fair_name }}</a></h1>
        <ul>
        <li>{{ last_fair.first_start_time|date:"l"}}, {{ last_fair.first_start_time.date }}: {{ last_fair.first_start_time.time }} to {{ last_fair.first_end_time.time }} ET</li>

        {% if last_fair.second_start_time %}
            <li>{{ last_fair.second_start_time|date:"l"}}, {{ last_fair.second_start_time.date }}: {{ last_fair.second_start_time.time }} to {{ last_fair.second_end_time.time }} ET</li>
        {% endif %}

        {% if last_fair.third_start_time %}
            <li>{{ last_fair.third_start_time|date:"l"}}, {{ last_fair.third_start_time.date }}: {{ last_fair.third_start_time.time }} to {{ last_fair.third_end_time.time }} ET</li>
        {% endif %}
        </ul>

        <p><b>Location:</b> {{ last_fair.address }} {{ last_fair.city }}, {{ last_fair.state }}</p>
        </div>
        <div class="column-12"><hr></div>
    {% endif %}

    <hr>

    <h1>Upcoming Craft Fairs:</h1>
    <p>Come see our items in person and shop without shipping fees!</p>

    {% for fair in fairs_future %}

        <div class="column-12" >

        <img class="col6" id="fair_pic" src="{{ fair.photo_fair }}" width="{{ fair.photo_fair_width }}" height="{{ fair.photo_fair_height }}">
        <h2><a href="{{ fair.fair_url }}">{{ fair.fair_name }}</a></h2>

        <ul>
        <li>{{ fair.first_start_time|date:"l"}}, {{ fair.first_start_time.date }}: {{ fair.first_start_time.time }} to {{ fair.first_end_time.time }} ET</li>

        {% if fair.second_start_time %}
            <li>{{ fair.second_start_time|date:"l"}}, {{ fair.second_start_time.date }}: {{ fair.second_start_time.time }} to {{ fair.second_end_time.time }} ET</li>
        {% endif %}

        {% if fair.third_start_time %}
            <li>{{ fair.third_start_time|date:"l"}}, {{ fair.third_start_time.date }}: {{ fair.third_start_time.time }} to {{ fair.third_end_time.time }} ET</li>
        {% endif %}
        </ul>

        <p><b>Location:</b> {{ fair.address }} {{ fair.city }}, {{ fair.state }}</p>
        </div>
        <div class="column-12"><hr></div>
    {% endfor %}

    <div class="column-12"><h1 id="spacer">Craft Fairs we have attended:</h1></div>


    {% for fair in fairs_past %}
        <div class="column-12" id="craft-fairs">
        <img class="col6" id="fair_pic" src="{{ fair.photo_fair }}" width="{{ fair.photo_fair_width }}" height="{{ fair.photo_fair_height }}">
        <h2><a href="{{ fair.fair_url }}">{{ fair.fair_name }}</a></h2>

        <ul>
        <li>{{ fair.first_start_time|date:"l"}}, {{ fair.first_start_time.date }}: {{ fair.first_start_time.time }} to {{ fair.first_end_time.time }} ET</li>

        {% if fair.second_start_time %}
            <li>{{ fair.second_start_time|date:"l"}}, {{ fair.second_start_time.date }}: {{ fair.second_start_time.time }} to {{ fair.second_end_time.time }} ET</li>
        {% endif %}

        {% if fair.third_start_time %}
            <li>{{ fair.third_start_time|date:"l"}}, {{ fair.third_start_time.date }}: {{ fair.third_start_time.time }} to {{ fair.third_end_time.time }} ET</li>
        {% endif %}
        </ul>
        <p><b>Location:</b> {{ fair.address }} {{ fair.city }}, {{ fair.state }}</p>

            <p><a href="{% url 'sold_at_fair' fair.id %}">What sold at {{ fair.fair_name }}?</a></p>

        </div>
        <div class="column-12"><hr></div>
    {% endfor %}


{% endblock %}

django_project/templates/mmestore/sold_at_fair.html
{% extends "base.html" %}

{% block title %}Mme's Creations: Items sold at {{ fair }} {%  endblock %}

{% block full-content %}
<h1>Items sold at {{ fair }}</h1>

    {% if items %}

        {% for item in items %}
            <div id="cat_break" class="column-12"></div>

                <div class="column-12" id="cat_item">
                    <div class="column-6">
                    <img class="col6" src="{{ item.photo_front }}" alt="{{ item.description }}">
                    </div>

                    <div class="column-6">
                    <h4>{{ item.category }} - {{ item.description }}</h4>
                    <h4>Item Number: {{ item.item_number }}</h4>
                    </div>
                </div>
            <br clear="both">


        {% endfor %}

    {%  else %}
        <h3>No items currently listed in the database sold at {{ fair }}.</h3>
    {% endif %}
{% endblock %}